### PR TITLE
Incompatible with apps using AndroidX

### PR DESCRIPTION
**Pull request by moconnell9**
Android support libraries have been moved to the `androidx` namespace. Please update.

https://developer.android.com/jetpack/androidx/migrate

### CODE REVIEW

**Comment by darryncampbell** [comment]
Thank you for the contribution!  I am sorry about the delayed reply but I have just come back from holiday.  Once I get through all my backlog that built up whilst I was away I will get review this.

**Comment by darryncampbell** [comment]
I did some testing and it works as long as the target SDK is 28 or higher, so I had to update my test application.  I presume this is OK but just double checking this is expected behaviour before I merge the request?  I have been out of touch with the wider Cordova community recently, hence my request for clarification that this is OK.  Thanks again.

**Comment by moconnell9** [comment]
Thank you for testing this so quickly! Yes 28 is [standard right now](https://stackoverflow.com/questions/57007653/warning-android-api-level-28-with-ionic-v3-and-cordova-6-3-0). You may want to add `<preference name="android-targetSdkVersion" value="28" />` but it's not required.

**Comment by darryncampbell** [comment]
Great, thanks! I will bump the version to 1.2.0 and post to npm

**Pull request merged**
